apiVersion: v1
kind: Service
metadata:
  name: meu-servico
spec:
  selector:
    app: meu-app
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000  # Escolha uma porta disponível para o nodePort
  type: NodePort
