apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-deployment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meu-app
  template:
    metadata:
      labels:
        app: meu-app
    spec:
      containers:
      - name: meu-container
        image: lukasdext01/app_flask:latest
        ports:
        - containerPort: 80
